version: "3.8"

services:
  android_builder:
    build:
      context: "."
      dockerfile: "./Dockerfile"
    image: "android_builder"
    container_name: "android_builder"
    volumes:
      - ./apk_build:/workdir/android/app/build/outputs/apk
    privileged: true
    networks:
      - "android_network"

networks:
  android_network:
    driver: "bridge"
