version: "3.8"

services:
    reactapp:
        build:
            context: "."
            dockerfile: "./Dockerfile"
        image: "jeuxreact"
        container_name: "reactapp"
        privileged: false
        restart: "always"
        stdin_open: true
        tty: true
        ports:
            - "80:1880"
        networks:
            - "network"

networks:
    network:
        driver: "bridge"

