name: Build Android APK with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    env:
        BUILD_CONF: docker-compose-build.yml
        BUILD_IMAGE: capacitor_builder
    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Android APK
        run: |
          echo "Building Android APK..."
          mkdir apk_build
          docker-compose -f $BUILD_CONFI run $BUILD_IMAGE  # Builds APK using the docker-compose

      - name: Upload Android APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: apk_build/debug/app-debug.apk  

