name: Build Android APK and iOS IPA with Docker Compose

on:
  push:
    branches:
      - "*"
  pull_request:
    paths:
      - .dockerignore
      - build-android.sh
      - build-ios.sh
      - build.Dockerfile
      - docker-compose-android.yml
      - docker-compose-ios.yml
      - android/**/*
      - ios/**/*
      - src/**/*

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12-dind
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y git docker-compose

      - name: Build Android APK
        run: |
          echo "Building Android APK..."
          rm -rf apk_build
          mkdir apk_build
          docker-compose -f docker-compose-android.yml up --build

      - name: Upload Android APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: apk_build/debug/app-debug.apk  

  build-ios:
    name: Build iOS IPA
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install cocoapods
          npm install

      - name: Build iOS IPA
        run: |
          echo "Building iOS IPA..."
          rm -rf ipa_build
          mkdir ipa_build
          docker-compose -f docker-compose-ios.yml up --build

      - name: Upload iOS IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.ipa
          path: ipa_build/ios/app-debug.ipa
