name: Build Android APK with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .dockerignore
      - build-android.sh
      - build-ios.sh
      - build.Dockerfile
      - docker-compose-build.yml
      - android/**/*
      - ios/**/*
      - src/**/*

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y git docker-compose

      - name: Build Android APK
        run: |
          echo "Building Android APK..."
          mkdir apk_build
          docker-compose -f docker-compose-build.yml up --build

      - name: Upload Android APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: apk_build/debug/app-debug.apk  

